# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: share/doc/conf.py

# Optionally build your docs in additional formats such as PDF
formats: []

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   install:
   - requirements: share/doc/requirements.txt
